# Generated by Django 4.1.7 on 2023-06-07 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Med', '0008_appointment_pay_amount'),
        ('users', '0007_remove_profile_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prescriptions',
        ),
        migrations.AddField(
            model_name='profile',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presc', to='Med.prescription'),
        ),
    ]
