# Generated by Django 4.1.7 on 2023-06-07 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Med', '0008_appointment_pay_amount'),
        ('users', '0008_remove_profile_prescriptions_profile_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presc', to='Med.prescription'),
        ),
    ]
